[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Trishna Kashyap", email = "trishna0703@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "fastapi[standard]>=0.141.1",
    "google-auth>=2.56.3",
    "psycopg>=3.3.4",
    "pydantic-settings>=2.15.0",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.3",
]
