"""updated evidence model

Revision ID: 027e5bcb550d
Revises: 23094337e5b3
Create Date: 2026-08-19 18:25:16.632301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027e5bcb550d'
down_revision: Union[str, Sequence[str], None] = '23094337e5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidences', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'evidences', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidences', type_='foreignkey')
    op.drop_column('evidences', 'user_id')
    # ### end Alembic commands ###
