"""updated concerns model

Revision ID: 23094337e5b3
Revises: 80a8cc3a6bea
Create Date: 2026-08-19 18:00:33.205010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23094337e5b3'
down_revision: Union[str, Sequence[str], None] = '80a8cc3a6bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_concerns', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'health_concerns', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_concerns', type_='foreignkey')
    op.drop_column('health_concerns', 'user_id')
    # ### end Alembic commands ###
