"""added ai schedule recommendations

Revision ID: 2a4537bd9195
Revises: 10bb99915b40
Create Date: 2026-09-11 14:08:32.006797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4537bd9195'
down_revision: Union[str, Sequence[str], None] = '10bb99915b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species_care_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(length=255), nullable=False),
    sa.Column('care_type', sa.String(length=100), nullable=False),
    sa.Column('knowledge', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_species_care_knowledge_species_type', 'species_care_knowledge', ['species', 'care_type'], unique=True)
    op.create_table('care_schedule_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('care_type', sa.String(length=100), nullable=False),
    sa.Column('frequency_type', sa.String(length=50), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.String(length=4000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generation_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('care_schedule_recommendations')
    op.drop_index('uq_species_care_knowledge_species_type', table_name='species_care_knowledge')
    op.drop_table('species_care_knowledge')
    # ### end Alembic commands ###
