"""updated concerns

Revision ID: 5ce4627e6ad8
Revises: d04e76044fd8
Create Date: 2026-08-23 22:53:39.472963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce4627e6ad8'
down_revision: Union[str, Sequence[str], None] = 'd04e76044fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_concerns', sa.Column('initial_evidence_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'health_concerns', 'evidences', ['initial_evidence_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_concerns', type_='foreignkey')
    op.drop_column('health_concerns', 'initial_evidence_id')
    # ### end Alembic commands ###
