"""created care event scheduling schemas

Revision ID: 5ef6701012a3
Revises: 52e77fe6931d
Create Date: 2026-09-01 09:41:39.137173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ef6701012a3'
down_revision: Union[str, Sequence[str], None] = '52e77fe6931d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('care_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('frequency_type', sa.String(length=50), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_occurrence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('google_calendar_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_account_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('care_schedule_calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_schedule_id', sa.Integer(), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('event_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['care_schedule_id'], ['care_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('care_schedule_id')
    )
    op.add_column('care_events', sa.Column('care_schedule_id', sa.Integer(), nullable=True))
    op.add_column('care_events', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('care_events', sa.Column('source', sa.String(length=20), nullable=False))
    op.alter_column('care_events', 'occurred_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'care_events', 'care_schedules', ['care_schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'care_events', type_='foreignkey')
    op.alter_column('care_events', 'occurred_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('care_events', 'source')
    op.drop_column('care_events', 'status')
    op.drop_column('care_events', 'care_schedule_id')
    op.drop_table('care_schedule_calendar_events')
    op.drop_table('google_calendar_connections')
    op.drop_table('care_schedules')
    # ### end Alembic commands ###
