"""updated plant identification

Revision ID: 5f65a24f5bc1
Revises: 8b30201192b2
Create Date: 2026-08-21 18:04:41.969652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f65a24f5bc1'
down_revision: Union[str, Sequence[str], None] = '8b30201192b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_identifications', 'concern_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_identifications', 'concern_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
