"""update in assessment and interaction

Revision ID: 646ac98afd77
Revises: c098176518be
Create Date: 2026-08-22 16:00:46.757778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '646ac98afd77'
down_revision: Union[str, Sequence[str], None] = 'c098176518be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessments', 'problem',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('assessments', 'problem_cause',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('assessments', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessments', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('assessments', 'problem_cause',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('assessments', 'problem',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    # ### end Alembic commands ###
