"""updated recommendations

Revision ID: 6a293fa341cf
Revises: f0f376030fb0
Create Date: 2026-08-25 22:32:14.933419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a293fa341cf'
down_revision: Union[str, Sequence[str], None] = 'f0f376030fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('generation_id', sa.String(length=36), nullable=False))
    op.add_column('recommendations', sa.Column('option_id', sa.String(length=100), nullable=False))
    op.add_column('recommendations', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('recommendations', sa.Column('title', sa.String(length=300), nullable=False))
    op.add_column('recommendations', sa.Column('summary', sa.String(length=1000), nullable=False))
    op.add_column('recommendations', sa.Column('steps', sa.JSON(), nullable=False))
    op.add_column('recommendations', sa.Column('materials', sa.JSON(), nullable=False))
    op.add_column('recommendations', sa.Column('frequency', sa.String(length=300), nullable=True))
    op.add_column('recommendations', sa.Column('duration', sa.String(length=300), nullable=True))
    op.add_column('recommendations', sa.Column('caution', sa.String(length=1000), nullable=True))
    op.add_column('recommendations', sa.Column('expected_result', sa.String(length=1000), nullable=False))
    op.add_column('recommendations', sa.Column('recommendation_score', sa.Integer(), nullable=False))
    op.add_column('recommendations', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('recommendations', sa.Column('selected_at', sa.DateTime(), nullable=True))
    op.add_column('recommendations', sa.Column('schema_version', sa.String(length=30), nullable=False))
    op.add_column('recommendations', sa.Column('model', sa.String(length=200), nullable=False))
    op.add_column('recommendations', sa.Column('prompt_version', sa.String(length=30), nullable=False))
    op.add_column('recommendations', sa.Column('input_payload', sa.JSON(), nullable=False))
    op.add_column('recommendations', sa.Column('response_payload', sa.JSON(), nullable=False))
    op.add_column('recommendations', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('recommendations_assessment_id_key'), 'recommendations', type_='unique')
    op.create_index(op.f('ix_recommendations_generation_id'), 'recommendations', ['generation_id'], unique=False)
    op.drop_column('recommendations', 'recommendation_type')
    op.drop_column('recommendations', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    op.add_column('recommendations', sa.Column('recommendation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_recommendations_generation_id'), table_name='recommendations')
    op.create_unique_constraint(op.f('recommendations_assessment_id_key'), 'recommendations', ['assessment_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('recommendations', 'created_at')
    op.drop_column('recommendations', 'response_payload')
    op.drop_column('recommendations', 'input_payload')
    op.drop_column('recommendations', 'prompt_version')
    op.drop_column('recommendations', 'model')
    op.drop_column('recommendations', 'schema_version')
    op.drop_column('recommendations', 'selected_at')
    op.drop_column('recommendations', 'status')
    op.drop_column('recommendations', 'recommendation_score')
    op.drop_column('recommendations', 'expected_result')
    op.drop_column('recommendations', 'caution')
    op.drop_column('recommendations', 'duration')
    op.drop_column('recommendations', 'frequency')
    op.drop_column('recommendations', 'materials')
    op.drop_column('recommendations', 'steps')
    op.drop_column('recommendations', 'summary')
    op.drop_column('recommendations', 'title')
    op.drop_column('recommendations', 'position')
    op.drop_column('recommendations', 'option_id')
    op.drop_column('recommendations', 'generation_id')
    # ### end Alembic commands ###
