"""add deleted flag to care schedules

Revision ID: 78a7604ae730
Revises: c901ba7167fd
Create Date: 2026-09-04 12:47:02.648856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78a7604ae730'
down_revision: Union[str, Sequence[str], None] = 'c901ba7167fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_schedules', sa.Column('deleted_by_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_schedules', 'deleted_by_user')
    # ### end Alembic commands ###
