"""updated concerns model

Revision ID: 80a8cc3a6bea
Revises: f7581c5b23c7
Create Date: 2026-08-19 17:21:56.208704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80a8cc3a6bea'
down_revision: Union[str, Sequence[str], None] = 'f7581c5b23c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('health_concerns', 'plant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('health_concerns', 'plant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
