"""updated schedules

Revision ID: 8649e8d0aa0d
Revises: 5ac50bfb66a9
Create Date: 2026-09-11 06:52:21.112396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8649e8d0aa0d'
down_revision: Union[str, Sequence[str], None] = '5ac50bfb66a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('care_schedule_calendar_events_care_schedule_id_key'), 'care_schedule_calendar_events', type_='unique')
    op.create_index('ix_care_schedule_calendar_events_schedule_start', 'care_schedule_calendar_events', ['care_schedule_id', 'event_start_at'], unique=False)
    op.create_index('uq_care_schedule_active_event', 'care_schedule_calendar_events', ['care_schedule_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_care_schedule_active_event', table_name='care_schedule_calendar_events', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('ix_care_schedule_calendar_events_schedule_start', table_name='care_schedule_calendar_events')
    op.create_unique_constraint(op.f('care_schedule_calendar_events_care_schedule_id_key'), 'care_schedule_calendar_events', ['care_schedule_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
