"""altered schedules

Revision ID: 88a6115def92
Revises: f767ce0929fc
Create Date: 2026-09-04 19:04:31.012224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a6115def92'
down_revision: Union[str, Sequence[str], None] = 'f767ce0929fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('care_schedules', 'deleted_by_user',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('care_schedules', 'deleted_by_user',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
