"""updated concerns

Revision ID: 8b30201192b2
Revises: ff360979bf1b
Create Date: 2026-08-20 14:55:19.320177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8b30201192b2"
down_revision: Union[str, Sequence[str], None] = "ff360979bf1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "health_concerns",
        sa.Column("submission_id", sa.String(length=36), nullable=True),
    )

    op.execute(
        "UPDATE health_concerns "
        "SET submission_id = gen_random_uuid()::text "
        "WHERE submission_id IS NULL"
    )

    op.alter_column(
        "health_concerns",
        "submission_id",
        nullable=False,
    )

    op.create_unique_constraint(
        "uq_health_concerns_submission_id", "health_concerns", ["submission_id"]
    )
    op.drop_constraint(
        op.f("plant_identifications_concern_id_key"),
        "plant_identifications",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("plant_identifications_concern_id_key"),
        "plant_identifications",
        ["concern_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(None, "health_concerns", type_="unique")
    op.drop_column("health_concerns", "submission_id")
    # ### end Alembic commands ###
