"""updated user sessions

Revision ID: 94f7c22d86cb
Revises: a45b27c00677
Create Date: 2026-09-01 15:06:03.711946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f7c22d86cb'
down_revision: Union[str, Sequence[str], None] = 'a45b27c00677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('oauth_code_verifier', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'oauth_code_verifier')
    # ### end Alembic commands ###
