"""updated user sessions

Revision ID: a3bf392221e4
Revises: 94f7c22d86cb
Create Date: 2026-09-01 15:14:39.757127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3bf392221e4'
down_revision: Union[str, Sequence[str], None] = '94f7c22d86cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('oauth_return_to', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'oauth_return_to')
    # ### end Alembic commands ###
