"""updated user sessions

Revision ID: a45b27c00677
Revises: 5ef6701012a3
Create Date: 2026-09-01 13:52:21.027363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45b27c00677'
down_revision: Union[str, Sequence[str], None] = '5ef6701012a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('oauth_state', sa.String(length=128), nullable=True))
    op.add_column('sessions', sa.Column('oauth_state_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'oauth_state_expires_at')
    op.drop_column('sessions', 'oauth_state')
    # ### end Alembic commands ###
