"""update in assessment and interaction

Revision ID: c098176518be
Revises: 5f65a24f5bc1
Create Date: 2026-08-22 13:20:43.658459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c098176518be'
down_revision: Union[str, Sequence[str], None] = '5f65a24f5bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_messages', sa.Column('sequence', sa.Integer(), nullable=False))
    op.add_column('assessment_messages', sa.Column('message_type', sa.String(length=50), nullable=False))
    op.add_column('assessment_messages', sa.Column('payload', sa.JSON(), nullable=False))
    op.alter_column('assessment_messages', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_column('assessment_messages', 'message')
    op.add_column('assessments', sa.Column('current_interaction_id', sa.Integer(), nullable=True))
    op.alter_column('assessments', 'confidence',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('assessments', 'explanation',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('assessments', 'created_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    op.create_foreign_key(None, 'assessments', 'assessment_messages', ['current_interaction_id'], ['id'])
    op.alter_column('care_events', 'occurred_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('evidences', 'recorded_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('health_concerns', 'occurred_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('health_concerns', 'reported_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('outcomes', 'recorded_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('plant_photos', 'captured_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('plant_photos', 'uploaded_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('plant_photos', 'expires_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('plants', 'added_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('recommendations', 'performed_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'joined_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'joined_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('recommendations', 'performed_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('plants', 'added_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('plant_photos', 'expires_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('plant_photos', 'uploaded_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('plant_photos', 'captured_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('outcomes', 'recorded_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('health_concerns', 'reported_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('health_concerns', 'occurred_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('evidences', 'recorded_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('care_events', 'occurred_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.alter_column('assessments', 'created_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('assessments', 'explanation',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('assessments', 'confidence',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('assessments', 'current_interaction_id')
    op.add_column('assessment_messages', sa.Column('message', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    op.alter_column('assessment_messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('assessment_messages', 'payload')
    op.drop_column('assessment_messages', 'message_type')
    op.drop_column('assessment_messages', 'sequence')
    # ### end Alembic commands ###
