"""initial schema

Revision ID: c3462cd5268c
Revises:
Create Date: 2026-08-18 15:17:18.569589

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c3462cd5268c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("joined_on", sa.Date(), nullable=False),
        sa.Column("planting_experience", sa.String(length=20), nullable=True),
        sa.Column("avatar", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "shelves",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("shelf_type", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_user_shelf_name"),
    )
    op.create_table(
        "plants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("species", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("pot_size", sa.Float(), nullable=True),
        sa.Column("added_on", sa.Date(), nullable=False),
        sa.Column("location_type", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("avatar_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_user_plant_name"),
    )
    op.create_table(
        "shelf_plants",
        sa.Column("shelf_id", sa.Integer(), nullable=False),
        sa.Column("plant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shelf_id"],
            ["shelves.id"],
        ),
        sa.PrimaryKeyConstraint("shelf_id", "plant_id"),
    )
    op.create_table(
        "evidences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evidence_type", sa.String(length=40), nullable=False),
        sa.Column("evidence_value", sa.String(length=500), nullable=False),
        sa.Column("value_type", sa.String(length=50), nullable=False),
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plant_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plant_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("photo_url", sa.String(length=500), nullable=False),
        sa.Column("captured_on", sa.Date(), nullable=True),
        sa.Column("uploaded_on", sa.Date(), nullable=False),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(
        "fk_plants_avatar_id",
        "plants",
        "plant_photos",
        ["avatar_id"],
        ["id"],
    )
    op.create_table(
        "care_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plant_id", sa.Integer(), nullable=False),
        sa.Column("care_type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence_photos",
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("evidence_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidences.id"],
        ),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["plant_photos.id"],
        ),
        sa.PrimaryKeyConstraint("photo_id", "evidence_id"),
    )
    op.create_table(
        "health_concerns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plant_id", sa.Integer(), nullable=False),
        sa.Column("initial_context", sa.String(length=2000), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("reported_on", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concern_id", sa.Integer(), nullable=False),
        sa.Column("problem", sa.String(length=2000), nullable=False),
        sa.Column("problem_cause", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.String(length=50), nullable=False),
        sa.Column("explanation", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_on", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concern_id"],
            ["health_concerns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "concern_evidences",
        sa.Column("concern_id", sa.Integer(), nullable=False),
        sa.Column("evidence_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concern_id"],
            ["health_concerns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidences.id"],
        ),
        sa.PrimaryKeyConstraint("concern_id", "evidence_id"),
    )
    op.create_table(
        "outcomes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concern_id", sa.Integer(), nullable=False),
        sa.Column("outcome_type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concern_id"],
            ["health_concerns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concern_id", sa.Integer(), nullable=False),
        sa.Column("recommendation_type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("performed_on", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["concern_id"],
            ["health_concerns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assessment_evidences",
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column("evidence_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidences.id"],
        ),
        sa.PrimaryKeyConstraint("assessment_id", "evidence_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assessment_evidences")
    op.drop_table("evidence_photos")
    op.drop_table("concern_evidences")
    op.drop_table("recommendations")
    op.drop_table("outcomes")
    op.drop_table("assessments")
    op.drop_table("health_concerns")
    op.drop_table("care_events")
    op.drop_table("shelf_plants")
    op.drop_constraint(
        "fk_plants_avatar_id",
        "plants",
        type_="foreignkey",
    )
    op.drop_table("plant_photos")
    op.drop_table("plants")
    op.drop_table("shelves")
    op.drop_table("evidences")
    op.drop_table("users")
    # ### end Alembic commands ###
