"""updated care schedule

Revision ID: c901ba7167fd
Revises: dbce042f66c3
Create Date: 2026-09-04 12:31:20.770267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c901ba7167fd'
down_revision: Union[str, Sequence[str], None] = 'dbce042f66c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_care_schedule_plant_care_type', 'care_schedules', ['plant_id', 'care_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_care_schedule_plant_care_type', 'care_schedules', type_='unique')
    # ### end Alembic commands ###
