"""updated care schedule

Revision ID: dbce042f66c3
Revises: a3bf392221e4
Create Date: 2026-09-04 11:00:34.342838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbce042f66c3'
down_revision: Union[str, Sequence[str], None] = 'a3bf392221e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_schedules', sa.Column('auto_schedule', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_schedules', 'auto_schedule')
    # ### end Alembic commands ###
