"""updated schedules

Revision ID: e4b5a0732ce9
Revises: 8649e8d0aa0d
Create Date: 2026-09-11 07:29:09.970887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b5a0732ce9'
down_revision: Union[str, Sequence[str], None] = '8649e8d0aa0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_events', sa.Column('was_action_taken', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_events', 'was_action_taken')
    # ### end Alembic commands ###
