"""updated schedules

Revision ID: ecb3a531577e
Revises: e4b5a0732ce9
Create Date: 2026-09-11 07:30:53.593963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb3a531577e'
down_revision: Union[str, Sequence[str], None] = 'e4b5a0732ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "care_events",
        "was_action_taken",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Boolean(),
        existing_nullable=False,
        postgresql_using="""
        CASE
            WHEN was_action_taken = 'true' THEN TRUE
            WHEN was_action_taken = 'false' THEN FALSE
            ELSE FALSE
        END
    """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('care_events', 'was_action_taken',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
