"""updated assessment

Revision ID: f0f376030fb0
Revises: 5ce4627e6ad8
Create Date: 2026-08-24 11:29:59.768048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f376030fb0'
down_revision: Union[str, Sequence[str], None] = '5ce4627e6ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcomes', sa.Column('recommendation_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'outcomes', ['recommendation_id'])
    op.drop_constraint(op.f('outcomes_concern_id_fkey'), 'outcomes', type_='foreignkey')
    op.create_foreign_key(None, 'outcomes', 'recommendations', ['recommendation_id'], ['id'])
    op.drop_column('outcomes', 'concern_id')
    op.add_column('recommendations', sa.Column('assessment_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'recommendations', ['assessment_id'])
    op.drop_constraint(op.f('recommendations_concern_id_fkey'), 'recommendations', type_='foreignkey')
    op.create_foreign_key(None, 'recommendations', 'assessments', ['assessment_id'], ['id'])
    op.drop_column('recommendations', 'concern_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('concern_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.create_foreign_key(op.f('recommendations_concern_id_fkey'), 'recommendations', 'health_concerns', ['concern_id'], ['id'])
    op.drop_constraint(None, 'recommendations', type_='unique')
    op.drop_column('recommendations', 'assessment_id')
    op.add_column('outcomes', sa.Column('concern_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'outcomes', type_='foreignkey')
    op.create_foreign_key(op.f('outcomes_concern_id_fkey'), 'outcomes', 'health_concerns', ['concern_id'], ['id'])
    op.drop_constraint(None, 'outcomes', type_='unique')
    op.drop_column('outcomes', 'recommendation_id')
    # ### end Alembic commands ###
