"""altered the unique constrain on schedule

Revision ID: f767ce0929fc
Revises: 78a7604ae730
Create Date: 2026-09-04 12:53:25.459701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f767ce0929fc'
down_revision: Union[str, Sequence[str], None] = '78a7604ae730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_care_schedule_plant_care_type'), 'care_schedules', type_='unique')
    op.create_index('uq_care_schedule_plant_care_type_active', 'care_schedules', ['plant_id', 'care_type'], unique=True, postgresql_where=sa.text('deleted_by_user IS false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_care_schedule_plant_care_type_active', table_name='care_schedules', postgresql_where=sa.text('deleted_by_user IS false'))
    op.create_unique_constraint(op.f('uq_care_schedule_plant_care_type'), 'care_schedules', ['plant_id', 'care_type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
