"""message and identitifation

Revision ID: ff360979bf1b
Revises: 027e5bcb550d
Create Date: 2026-08-20 09:42:41.011654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff360979bf1b'
down_revision: Union[str, Sequence[str], None] = '027e5bcb550d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_identifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concern_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concern_id'], ['health_concerns.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concern_id')
    )
    op.create_table('assessment_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_messages')
    op.drop_table('plant_identifications')
    # ### end Alembic commands ###
